apiVersion: v1
kind: ConfigMap
metadata:
 name: aws-auth
 namespace: kube-system
data:
 mapRoles: |
   - rolearn:  arn:aws:iam::747565123955:role/eksctl-udacity-krishna-cluster-no-NodeInstanceRole-154HN4NU8UMEL
     username: system:node:{{EC2PrivateDNSName}}
     groups:
       - system:bootstrappers
       - system:nodes
